window.MappingSubdistSeed = [
    {
        "id":  "010213",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "010213",
        "namaKmmd":  "CV. Victor Wijaya (Binjai)",
        "titik":  "Binjai",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "CV. Victor Wijaya (Binjai)",
        "kodeBranch":  "3201",
        "branchEpm":  "Medan",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "010209",
        "parent":  "TIDAK",
        "parentKode":  "010211",
        "kodeKmmd":  "010209",
        "namaKmmd":  "PT. Adyajati Lestari (Medan Barat)",
        "titik":  "Medan",
        "groupType":  "Group",
        "namaGroup":  "PT. Adyajati Lestari Group",
        "namaSubdistGroup":  "PT. Adyajati Lestari Group",
        "kodeBranch":  "3201",
        "branchEpm":  "Medan",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-BVG",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true,
        "linkedAt":  "2026-06-01"
    },
    {
        "id":  "010207",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "010207",
        "namaKmmd":  "PT. Sancho Mitra Sejahtera (Medan Barat)",
        "titik":  "Medan Barat",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "PT. Sancho Mitra Sejahtera (Medan Barat)",
        "kodeBranch":  "3201",
        "branchEpm":  "Medan",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "010211",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "010211",
        "namaKmmd":  "PT. Adyajati Lestari (Medan Timur)",
        "titik":  "Medan Timur",
        "groupType":  "Group",
        "namaGroup":  "PT. Adyajati Lestari Group",
        "namaSubdistGroup":  "PT. Adyajati Lestari Group",
        "kodeBranch":  "3201",
        "branchEpm":  "Medan",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "010212",
        "parent":  "TIDAK",
        "parentKode":  "010211",
        "kodeKmmd":  "010212",
        "namaKmmd":  "PT. Adyajati Lestari (Tanjung Morawa)",
        "titik":  "Tanjung Morawa",
        "groupType":  "Group",
        "namaGroup":  "PT. Adyajati Lestari Group",
        "namaSubdistGroup":  "PT. Adyajati Lestari Group",
        "kodeBranch":  "3201",
        "branchEpm":  "Medan",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true,
        "linkedAt":  "2026-06-01"
    },
    {
        "id":  "330101",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "330101",
        "namaKmmd":  "PD. Bintang Lima (Batam)",
        "titik":  "Batam",
        "groupType":  "Group",
        "namaGroup":  "PD. Bintang Lima Group",
        "namaSubdistGroup":  "PD. Bintang Lima Group",
        "kodeBranch":  "3233",
        "branchEpm":  "Batam",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "350215",
        "parent":  "TIDAK",
        "parentKode":  "010211",
        "kodeKmmd":  "350215",
        "namaKmmd":  "PT. Adyajati Lestari (Kisaran)",
        "titik":  "Kisaran",
        "groupType":  "Group",
        "namaGroup":  "PT. Adyajati Lestari Group",
        "namaSubdistGroup":  "PT. Adyajati Lestari Group",
        "kodeBranch":  "3235",
        "branchEpm":  "Pematang Siantar",
        "region":  "RM I Sumbagut",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "040310",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "040310",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Jakarta Selatan)",
        "titik":  "Jakarta Selatan",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3204",
        "branchEpm":  "Jakarta 1",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "310103",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "310103",
        "namaKmmd":  "PT. Putra Bumi Asih (Bekasi)",
        "titik":  "Bekasi",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "PT. Putra Bumi Asih (Bekasi)",
        "kodeBranch":  "3231",
        "branchEpm":  "Bekasi",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "400306",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "400306",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Tangerang Kabupaten)",
        "titik":  "Cikupa",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3240",
        "branchEpm":  "Tangerang",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "400304",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "400304",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Tangerang Selatan)",
        "titik":  "Cipondoh",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3240",
        "branchEpm":  "Tangerang",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "400310",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "400310",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Jakarta Barat)",
        "titik":  "Jakarta Barat",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3240",
        "branchEpm":  "Tangerang",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "400309",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "400309",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Tangerang kota)",
        "titik":  "Rajeg",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3240",
        "branchEpm":  "Tangerang",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "400305",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "400305",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Serang)",
        "titik":  "Serang",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3240",
        "branchEpm":  "Tangerang",
        "region":  "RM II Jatabek",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "050311",
        "parent":  "TIDAK",
        "parentKode":  "400310",
        "kodeKmmd":  "050311",
        "namaKmmd":  "PT. Catur Sentosa Anugerah (Bandung Selatan-B)",
        "titik":  "Bandung Selatan",
        "groupType":  "Group",
        "namaGroup":  "PT. Catur Sentosa Anugerah Group",
        "namaSubdistGroup":  "PT. Catur Sentosa Anugerah Group",
        "kodeBranch":  "3205",
        "branchEpm":  "Bandung",
        "region":  "RM III Jabar",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "070118",
        "parent":  "TIDAK",
        "parentKode":  "360301",
        "kodeKmmd":  "070118",
        "namaKmmd":  "CV. Mitra Sejati Distribusi (Jombang-B)",
        "titik":  "Jombang",
        "groupType":  "Group",
        "namaGroup":  "CV. Mitra Sejati Distribusi Group",
        "namaSubdistGroup":  "CV. Mitra Sejati Distribusi Group",
        "kodeBranch":  "3207",
        "branchEpm":  "Surabaya 1",
        "region":  "RM IV Jatim",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "360301",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "360301",
        "namaKmmd":  "CV. Mitra Sejati Distribusi (Lamongan-B)",
        "titik":  "Lamongan",
        "groupType":  "Group",
        "namaGroup":  "CV. Mitra Sejati Distribusi Group",
        "namaSubdistGroup":  "CV. Mitra Sejati Distribusi Group",
        "kodeBranch":  "3236",
        "branchEpm":  "Surabaya 2",
        "region":  "RM IV Jatim",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "360302",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "360302",
        "namaKmmd":  "CV. Kompas Sejahtera (Surabaya-B)",
        "titik":  "Surabaya",
        "groupType":  "Group",
        "namaGroup":  "CV. Kompas Sejahtera Group",
        "namaSubdistGroup":  "CV. Kompas Sejahtera Group",
        "kodeBranch":  "3236",
        "branchEpm":  "Surabaya 2",
        "region":  "RM IV Jatim",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "090107",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "090107",
        "namaKmmd":  "CV. Sumber Agung (Makasar)",
        "titik":  "Makasar",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "CV. Sumber Agung (Makasar)",
        "kodeBranch":  "3209",
        "branchEpm":  "Makasar",
        "region":  "RM V Sulintim",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "100102",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "100102",
        "namaKmmd":  "UD. Sehat Indah (Gorontalo)",
        "titik":  "Gorontalo",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "UD. Sehat Indah (Gorontalo)",
        "kodeBranch":  "3210",
        "branchEpm":  "Manado",
        "region":  "RM V Sulintim",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "090135",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "090135",
        "namaKmmd":  "PT. Primatama Abadi Sentosa (Palopo)",
        "titik":  "Palopo",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "PT. Primatama Abadi Sentosa (Palopo)",
        "kodeBranch":  "3209",
        "branchEpm":  "Makasar",
        "region":  "RM V Sulintim",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190106",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "190106",
        "namaKmmd":  "CV. Trio Hutama (Magelang)",
        "titik":  "Magelang",
        "groupType":  "Group",
        "namaGroup":  "CV. Trio Hutama Group",
        "namaSubdistGroup":  "CV. Trio Hutama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190111",
        "parent":  "TIDAK",
        "parentKode":  "340307",
        "kodeKmmd":  "190111",
        "namaKmmd":  "PT. Global Berhasil Mandiri (Magelang)",
        "titik":  "Magelang",
        "groupType":  "Group",
        "namaGroup":  "PT. Gemilang Berkat Utama Group",
        "namaSubdistGroup":  "PT. Gemilang Berkat Utama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-BVG",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190108",
        "parent":  "TIDAK",
        "parentKode":  "190106",
        "kodeKmmd":  "190108",
        "namaKmmd":  "CV. Trio Hutama (Purworejo)",
        "titik":  "Purworejo",
        "groupType":  "Group",
        "namaGroup":  "CV. Trio Hutama Group",
        "namaSubdistGroup":  "CV. Trio Hutama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190112",
        "parent":  "TIDAK",
        "parentKode":  "190106",
        "kodeKmmd":  "190112",
        "namaKmmd":  "CV. Tiga Saudara (Wonosari)",
        "titik":  "Wonosari",
        "groupType":  "Group",
        "namaGroup":  "CV. Trio Hutama Group",
        "namaSubdistGroup":  "CV. Trio Hutama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190107",
        "parent":  "TIDAK",
        "parentKode":  "190106",
        "kodeKmmd":  "190107",
        "namaKmmd":  "CV. Trio Hutama (Wonosobo)",
        "titik":  "Wonosobo",
        "groupType":  "Group",
        "namaGroup":  "CV. Trio Hutama Group",
        "namaSubdistGroup":  "CV. Trio Hutama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "190109",
        "parent":  "TIDAK",
        "parentKode":  "340307",
        "kodeKmmd":  "190109",
        "namaKmmd":  "PT. Berhasil Sentosa Selalu (Yogya)",
        "titik":  "Yogya",
        "groupType":  "Group",
        "namaGroup":  "PT. Gemilang Berkat Utama Group",
        "namaSubdistGroup":  "PT. Gemilang Berkat Utama Group",
        "kodeBranch":  "3219",
        "branchEpm":  "Yogya",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-BVG",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "340307",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "340307",
        "namaKmmd":  "PT. Gemilang Berkat Utama (Solo Putih)",
        "titik":  "Solo",
        "groupType":  "Group",
        "namaGroup":  "PT. Gemilang Berkat Utama Group",
        "namaSubdistGroup":  "PT. Gemilang Berkat Utama Group",
        "kodeBranch":  "3234",
        "branchEpm":  "Solo",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "450201",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "450201",
        "namaKmmd":  "CV. Tjahyono Abadi (Kudus)",
        "titik":  "Kudus",
        "groupType":  "Group",
        "namaGroup":  "CV. Tjahyono Abadi Group",
        "namaSubdistGroup":  "CV. Tjahyono Abadi Group",
        "kodeBranch":  "3245",
        "branchEpm":  "Kudus",
        "region":  "RM VI Jateng",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "030220",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "030220",
        "namaKmmd":  "PT. Menara Nusantara Perkasa (Palembang)",
        "titik":  "Palembang",
        "groupType":  "Non Group",
        "namaGroup":  "Non Group",
        "namaSubdistGroup":  "PT. Menara Nusantara Perkasa (Palembang)",
        "kodeBranch":  "3203",
        "branchEpm":  "Palembang",
        "region":  "RM VII Sumbagsel",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "140216",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "140216",
        "namaKmmd":  "PT. Fajar Lampung (Bandar Lampung)",
        "titik":  "Bandar Lampung",
        "groupType":  "Group",
        "namaGroup":  "UD. Fajar Lampung Group",
        "namaSubdistGroup":  "UD. Fajar Lampung Group",
        "kodeBranch":  "3214",
        "branchEpm":  "Bandar Lampung",
        "region":  "RM VII Sumbagsel",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "140218",
        "parent":  "TIDAK",
        "parentKode":  "140216",
        "kodeKmmd":  "140218",
        "namaKmmd":  "PT. Fajar Lampung (Kota Bumi)",
        "titik":  "Kota Bumi",
        "groupType":  "Group",
        "namaGroup":  "UD. Fajar Lampung Group",
        "namaSubdistGroup":  "UD. Fajar Lampung Group",
        "kodeBranch":  "3214",
        "branchEpm":  "Bandar Lampung",
        "region":  "RM VII Sumbagsel",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "140217",
        "parent":  "TIDAK",
        "parentKode":  "140216",
        "kodeKmmd":  "140217",
        "namaKmmd":  "PT. Fajar Lampung (Metro)",
        "titik":  "Metro",
        "groupType":  "Group",
        "namaGroup":  "UD. Fajar Lampung Group",
        "namaSubdistGroup":  "UD. Fajar Lampung Group",
        "kodeBranch":  "3214",
        "branchEpm":  "Bandar Lampung",
        "region":  "RM VII Sumbagsel",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "110131",
        "parent":  "TIDAK",
        "parentKode":  "110103",
        "kodeKmmd":  "110131",
        "namaKmmd":  "PT. Sedulur Sukses Sejahtera (Ampah)",
        "titik":  "Ampah",
        "groupType":  "Group",
        "namaGroup":  "PT. Sejahtera Sukses Sejati Group",
        "namaSubdistGroup":  "PT. Sejahtera Sukses Sejati Group",
        "kodeBranch":  "3211",
        "branchEpm":  "Banjarmasin",
        "region":  "RM IX Kalimantan",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "110103",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "110103",
        "namaKmmd":  "PT. Sejahtera Sukses Sejati (Banjarmasin)",
        "titik":  "Banjarmasin",
        "groupType":  "Group",
        "namaGroup":  "PT. Sejahtera Sukses Sejati Group",
        "namaSubdistGroup":  "PT. Sejahtera Sukses Sejati Group",
        "kodeBranch":  "3211",
        "branchEpm":  "Banjarmasin",
        "region":  "RM IX Kalimantan",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "110106",
        "parent":  "TIDAK",
        "parentKode":  "110103",
        "kodeKmmd":  "110106",
        "namaKmmd":  "PT. Sedulur Sukses Sejahtera (Barabai)",
        "titik":  "Barabai",
        "groupType":  "Group",
        "namaGroup":  "PT. Sejahtera Sukses Sejati Group",
        "namaSubdistGroup":  "PT. Sejahtera Sukses Sejati Group",
        "kodeBranch":  "3211",
        "branchEpm":  "Banjarmasin",
        "region":  "RM IX Kalimantan",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "130118",
        "parent":  "TIDAK",
        "parentKode":  "130116",
        "kodeKmmd":  "130118",
        "namaKmmd":  "PT. Cahaya Mega Sofian (Bontang)",
        "titik":  "Bontang",
        "groupType":  "Group",
        "namaGroup":  "PT. Cahaya Mega Sofian Group",
        "namaSubdistGroup":  "PT. Cahaya Mega Sofian Group",
        "kodeBranch":  "3213",
        "branchEpm":  "Samarinda",
        "region":  "RM IX Kalimantan",
        "tipeKmmd":  "KMMD-C",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    },
    {
        "id":  "130116",
        "parent":  "YA",
        "parentKode":  null,
        "kodeKmmd":  "130116",
        "namaKmmd":  "PT. Cahaya Mega Sofian (Samarinda)",
        "titik":  "Samarinda",
        "groupType":  "Group",
        "namaGroup":  "PT. Cahaya Mega Sofian Group",
        "namaSubdistGroup":  "PT. Cahaya Mega Sofian Group",
        "kodeBranch":  "3213",
        "branchEpm":  "Samarinda",
        "region":  "RM IX Kalimantan",
        "tipeKmmd":  "KMMD-B",
        "alamat":  "",
        "npwp":  "",
        "ppn":  true,
        "pph":  true,
        "active":  true
    }
];

/** Master tambahan dari Bosnet yang belum di-mapping (untuk demo Tambah via LOV) */
window.BosnetKmmdExtra = [
    {
        "kodeKmmd": "990101",
        "namaKmmd": "CV. Demo Bosnet Alpha (Belawan)",
        "titik": "Belawan",
        "groupType": "Group",
        "namaGroup": "CV. Demo Bosnet Alpha Group",
        "parent": "YA",
        "kodeBranch": "3201",
        "branchEpm": "Medan",
        "region": "RM I Sumbagut",
        "tipeKmmd": "KMMD-B",
        "active": true
    },
    {
        "kodeKmmd": "990102",
        "namaKmmd": "PT. Demo Bosnet Beta (Pematangsiantar)",
        "titik": "Pematangsiantar",
        "groupType": "Non Group",
        "namaGroup": "Non Group",
        "parent": "YA",
        "kodeBranch": "3201",
        "branchEpm": "Medan",
        "region": "RM I Sumbagut",
        "tipeKmmd": "KMMD-C",
        "active": true
    },
    {
        "kodeKmmd": "990103",
        "namaKmmd": "UD. Demo Bosnet Gamma (Tebing Tinggi)",
        "titik": "Tebing Tinggi",
        "groupType": "Group",
        "namaGroup": "UD. Demo Bosnet Gamma Group",
        "parent": "YA",
        "kodeBranch": "3201",
        "branchEpm": "Medan",
        "region": "RM I Sumbagut",
        "tipeKmmd": "KMMD-BVG",
        "active": true
    }
];
